[theme]
primaryColor = "#10B981"
backgroundColor = "#F0F9FF"
secondaryBackgroundColor = "#F9FAFB"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false
